### ISSUE TITLE
是否考虑做一个exporter的接口？

### ISSUE THREAD

**Issue by my6889** [flydoos/BYDCarHelper#10]
是否考虑做一个exporter的接口，展示一些常用的数据，例如能耗、里程、续航等，方便通过prometheus和grafana来收集和展示。

**Comment by flydoos** [comment]
> 是否考虑做一个exporter的接口，展示一些常用的数据，例如能耗、里程、续航等，方便通过prometheus和grafana来收集和展示。

暂不考虑，你可以自己解析本地Data目录下的数据实现
