### ISSUE TITLE
如果只需要签到功能，能否单独剥离出相关模块?

### ISSUE THREAD

**Issue by hidetag** [flydoos/BYDCarHelper#11]
想挂青龙去实现自动签到，我看介绍里有 cookie 自动续期和签到，老哥能否开源相关的 cookie 刷新与签到的 api 接口？如果能再介绍下如何抓cookie 就更好了（不用 PC 微信更好）

**Comment by flydoos** [comment]
> 想挂青龙去实现自动签到，我看介绍里有 cookie 自动续期和签到，老哥能否开源相关的 cookie 刷新与签到的 api 接口？如果能再介绍下如何抓cookie 就更好了（不用 PC 微信更好）

实现原理不同，有些操作需要依赖微信小程序，所以不能用青龙面板/POST接口直接实现。

但是，后期可能会考虑做一个独立的Windows桌面程序，用于支持“微信各种小程序自动签到程序”，其实现在最新版的BYD车辆助手也可以实现，只是功能不太灵活罢了
