### ISSUE TITLE
I bought byd tang 2023 chinese version, 

### ISSUE THREAD

**Issue by Anassanad** [flydoos/BYDCarHelper#13]
is there any way to change the software from chinese to glabal version so i can use the voice assistant and maps?
is there any way to connect my car to the phone app, i dont have chinease phone number.
bty, i live in jordan

有没有办法将软件从中文版更改为Glabal版本，以便我可以使用语音助手和地图？
有没有办法将我的车连接到手机应用程序，我没有 Chinease 电话号码。
顺便说一句，我住在约旦

**Comment by flydoos** [comment]
![1711524989152](https://github.com/flydoos/BYDCarHelper/assets/3932827/9f069adc-df5a-4043-ae1a-53213eff82f9)
上面的截图是BYD DiLink UI 4.0版本的，如果你的车子是 UI 3.0 版本，可能有点不同，但是你可以参考一下，只要你看到“语言”这个单词，就表示是“Language”，你可以尝试一下~~

**Comment by Anassanad** [comment]
感谢您的回复
我有 DiLink 5.0。
但是这个解决方案不会将语音助手更改为英语，我需要将地图和语音命令更改为英语，因为我不会说中文。


thank you for your respond
i have DiLink 5.0.
but this solution will not change the voice assistant to english, i need to change maps and voice commands to english because i don't speak chinese.

**Comment by flydoos** [comment]
我咨询过BYD官方客服，他们说语音助手不支持英语，除非你买的就是海外版本汽车，否则确实只能支持中文语音控制

**Comment by flydoos** [comment]
其实，你可以买一个CarPlay，其实也可以满足你的要求。我之前看过海外用户购买中国版本的BYD汽车，也是通过购买CarPlay使用的，虽然没有原生的那么方便

**Comment by Anassanad** [comment]
有没有办法 root 该软件并安装全球版本？

**Comment by flydoos** [comment]
不行的，比亚迪汽车ROOT刷机的时候，要求BYD官方工作人员扫描二维码以后才可以解锁经刷机（重装系统），如果你不喜欢CarPlay，那你只能自己开发一个APK应用程序，然后安装到汽车Pad上面，实现语音控制，BYD官方有提供SDK以及API接口（但是国外用户不知道能不能使用这些API接口，因为注册账号的时候就要求提供身份证实名认证）

比亚迪API文档地址：https://oip.byd.com/addons/cms/document/index

**Comment by Anassanad** [comment]
我听说俄罗斯有人设法在中国版汽车上安装了全球版DiLink，这怎么可能？
