### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by hthre7** [flydoos/BYDCarHelper#14]
planning to localize the app?

**Comment by flydoos** [comment]
这款软件没有必要支持多国语言，因为BYD汽车需要绑定中国手机号，外国人估计没办法使用。其次，这款软件需要安装中国版本的“WeChat”，然后绑定“微信”公众号才能使用，估计你们也没有这个使用条件，所以没必要进行翻译

**Comment by flydoos** [comment]
> planning to localize the app?

最后，如果你确定自己能够使用这款软件，我愿意花时间支持英文语言，你可以先试试能不能用吧
