### ISSUE TITLE
通知的车型不正确

### ISSUE THREAD

**Issue by JinruiWang** [flydoos/BYDCarHelper#15]
我添加了钉钉推送后，测试推送收到的车型是：宋PLUS DM-i 旗舰型Plus，而我是唐DMi

**Comment by flydoos** [comment]
> 我添加了钉钉推送后，测试推送收到的车型是：宋PLUS DM-i 旗舰型Plus，而我是唐DMi

大哥，测试推送，是写死的一条固定消息内容。。。。内容全是写死的。。。。所以显示的是作者的车型，只是告诉你们有什么字段罢了

**Comment by flydoos** [comment]
有些人不会配置，测试推送，除了告诉你们有什么字段，最大用处就是验证，是否配置正常，能不能发送消息
