### ISSUE TITLE
[feature req]定时任务

### ISSUE THREAD

**Issue by noodle1983** [flydoos/BYDCarHelper#17]
作者&车友好!
能不能加一个定时任务的功能, 具体的user case如下:

[用例]
我的车一直用自己的充电桩晚上12点预约充电,  今年年中升级后有个bug,  插电预约充电会自动缓慢掉电(1%/小时, 我的是早期的混动80km小电池, 但充满之后不会掉),  去了几次4s都没搞好...
4s指望不上, 我自己在充电桩前装了一个定时开关, 0:00-8:00 定时打开, 发现车机会一直休眠, 一直睡过去, 除非用app刷一下车辆信息, 车辆被唤醒, 才开始充电.
所以我想加一个定时任务, 比如0点取一下车辆信息或者锁一下车, 把车唤醒. 

另外app之前还有个8:00签到的活动, 能不能把签到也做成一个可定时的任务.

**Comment by flydoos** [comment]
1、掉电是正常啊，我的车自从安装了“迪+”，开启了停车监控之后，每天掉电3%甚至更多。本来车子也是后台运行一些软件的，并非真的关机。
2、从功能上，如果只需要签到，可以开启界面上的“智能车况”，然后开启签到功能即可，可以满足你的要求
3、如需其他定制开发功能，加Q群390669197联系群主沟通
