### ISSUE TITLE
签到

### ISSUE THREAD

**Issue by squirrel51** [flydoos/BYDCarHelper#18]
车友 你好，我不需要怎么多功能，我只想要一个签到的功能，我看相关代码没有开源，能否提供一下签到接口的信息

**Comment by flydoos** [comment]
1、从功能上，如果只需要签到，可以开启界面上的“智能车况”，然后开启签到功能即可，可以满足你的要求
2、拒绝伸手党，源码需要付费，加Q群390669197联系群主沟通
