### ISSUE TITLE
代码有开源的打算吗？

### ISSUE THREAD

**Issue by Emrys5** [flydoos/BYDCarHelper#2]
代码有开源的打算吗？

**Comment by flydoos** [comment]
这个东西没什么技术含量的，花了2天临时搞出来的，代码写的很渣，没法见人，有需要的自己反编译一下就能看到代码

**Comment by Hero-King** [comment]
@flydoos  请教老哥 自动签到是怎么实现的

**Comment by flydoos** [comment]
> @flydoos 请教老哥 自动签到是怎么实现的

现在才看到这个提问，怎么在一个关闭的工单问题上提问~~

签到不是所见即所得么？以前旧版本的比亚迪自动签到，是打开指定URL实现自动签到，但是后面海洋系，王朝系小程序/APP拆分之后，这个方法仅适用于王朝系，于是海洋系的自动签到，需要用户自己先添加收藏，然后再模拟用户打开的形式实现
