### ISSUE TITLE
期待可以有获取车辆实时位置和把所有信息post到服务器的功能

### ISSUE THREAD

**Issue by lwh201314** [flydoos/BYDCarHelper#5]
想把软件里获取到的信息post到nodered导入HA来记录车辆的状态，nodered没法更新cookie只能靠它了，如果能post全部信息就更方便了。

**Comment by flydoos** [comment]
这个功能HA上面已经有人做过了，你可以搜下相关脚本，而且，PC端做这个定位意义不大，暂不考虑
