### ISSUE TITLE
机器人消息推送能否支持自定义连接地址

### ISSUE THREAD

**Issue by CnSuperYoung** [flydoos/BYDCarHelper#8]
如题，自己写后台服务，获取推送，通过自己的渠道统一转发

**Comment by flydoos** [comment]
> 如题，自己写后台服务，获取推送，通过自己的渠道统一转发

这个其实本来就已经支持了，并不需要我重新开发新功能，因为只要你参考钉钉/飞书 接收机器人消息的接口，实现相关方法就可以了，然后把URL改成你自己的URL网址
