### ISSUE TITLE
非常棒的软件，能不能独立出来一个签到的脚本？ 利用青龙面板，实现自动签到？

### ISSUE THREAD

**Issue by bai1xia** [flydoos/BYDCarHelper#9]
非常棒的软件，能不能独立出来一个签到的脚本？ 利用青龙面板，实现自动签到？

**Comment by flydoos** [comment]
> 非常棒的软件，能不能独立出来一个签到的脚本？ 利用青龙面板，实现自动签到？

实现原理不同，有些操作需要依赖微信小程序，所以不能用青龙面板实现。

但是，后期可能会考虑做一个独立的Windows桌面程序，用于支持“微信各种小程序自动签到程序”，其实现在最新版的BYD车辆助手也可以实现，只是功能不太灵活罢了
